### ISSUE TITLE
nuxt crashes on plugin install

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/ql-search#2]
**Describe the bug**
Nuxt apollo crashes when ql-search app is installed

**To Reproduce**
1. Install searchWP plugin
2. Install ql-search plugin

**Errors**
Nuxt crashes with error `Network error: Unexpected end of JSON input` visible from front end.

WP-Graphql crashes with error: 
```Fatal error: Uncaught TypeError: Argument 1 passed to WPGraphQL\SearchWP\Type_Registry::init() must be an instance of WPGraphQL\Registry\TypeRegistry, string given, called in /www/wp-includes/class-wp-hook.php on line 286 and defined in /www/wp-content/plugins/ql-search-master/includes/class-type-registry.php:20 Stack trace: #0 /www/wp-includes/class-wp-hook.php(286): WPGraphQL\SearchWP\Type_Registry->init('') #1 /www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /www/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /www/wp-content/plugins/wp-graphql/src/TypeRegistry.php(242): do_action('graphql_registe...') #4 /www/wp-content/plugins/wp-graphql/wp-graphql.php(517): WPGraphQL\TypeRegistry::init() #5 /www/wp-content/plugins/wp-graphql/src/Request.php(85): WPGraphQL::get_schema() #6 /www/wp-content/plugins/wp-graphql/src/Router.php(339): WPGraphQL\Request->__construct() #7 /www/wp-content/plugins/wp-graphql/src/Router.php(153): WPGraphQL\Router::process_http_request() #8 /www/wp-include in /www/wp-content/plugins/ql-search-master/includes/class-type-registry.php on line 20```

visible from `{wordpress-backend.com}/graphql`

**Expected behavior**
Plugin should not crash app

**Additional context**
I installed on two different projects and received the same error

**Comment by drewbaker** [comment]
See the screenshot. The only difference between the working one and the error is ql-search activated. 

![Screen Shot 2019-11-21 at 1 48 56 PM](https://user-images.githubusercontent.com/475015/69379672-c1bf6e80-0c65-11ea-9f5f-7a4a12a14965.png)
![Screen Shot 2019-11-21 at 1 49 16 PM](https://user-images.githubusercontent.com/475015/69379674-c1bf6e80-0c65-11ea-8c75-aa11dbabff72.png)

**Comment by dChiamp** [comment]
Here's a screenshot of the error displayed on frontend when plugin is activated:
![ql-search-apollo-error](https://user-images.githubusercontent.com/13562688/69379867-267ac900-0c66-11ea-9f03-f576a69c83d8.png)
